databaseType = "MySql"
id = "8b52a0b7-07aa-46ba-883c-fdf6ef5cfe3d"
name = "FlywayAutoPilot"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.development]
url = "jdbc:mysql://localhost:3306"
schemas = [ "flywayapdev" ]
displayName = "Development database"

[environments.test]
url = "jdbc:mysql://localhost:3306"
schemas = [ "flywayaptest" ]
displayName = "Test database"

[environments.prod]
url = "jdbc:mysql://localhost:3306"
schemas = [ "flywayapprod" ]
displayName = "Production database"

[environments.shadow]
url = "jdbc:mysql://localhost:3306"
schemas = [ "flywayapshadow" ]
displayName = "Shadow database"

[environments.check]
url = "jdbc:mysql://localhost:3306"
schemas = [ "flywayapcheck" ]
displayName = "Check database"
provisioner = "clean"

[environments.build]
url = "jdbc:mysql://localhost:3306"
schemas = [ "flywayapbuild" ]
displayName = "Build database"
provisioner = "clean"
