-- Script generated by Redgate Compare v1.37.1.951


-- deployment: Dropping renetest...
DROP TABLE renetest;


-- deployment: Creating priorityclients...
CREATE TABLE priorityclients (
    FirstName varchar(24) NOT NULL,
    LastName varchar(45) NULL,
    ClientID int NULL
);
ALTER TABLE priorityclients ADD PRIMARY KEY (FirstName);


-- deployment: Creating customers_customer_feedback.ClientID...
ALTER TABLE customers_customer_feedback ADD COLUMN ClientID int NULL;


-- deployment: Creating customers_customer.ClientID...
ALTER TABLE customers_customer ADD COLUMN ClientID int NULL;

