-- Script generated by Redgate Compare v1.37.1.951


-- deployment: Dropping priorityclients...
DROP TABLE priorityclients;


-- deployment: Creating renetest...
CREATE TABLE renetest (
    rene varchar(100) NULL
);


-- deployment: Dropping customers_customer_feedback.ClientID...
ALTER TABLE customers_customer_feedback DROP COLUMN ClientID;


-- deployment: Dropping customers_customer.ClientID...
ALTER TABLE customers_customer DROP COLUMN ClientID;

